defmodule Money.DDLTest do
  use ExUnit.Case, async: true

  doctest Money.DDL

  # These assertions pin the identifiers that exist in deployed
  # databases. The SQL is generated by localize_sql, so a change there
  # that renamed the composite type, a field or a function would break
  # every consumer's migrations; that must fail here rather than in
  # someone else's database.
  describe "the money_with_currency type" do
    test "is created with its established name and fields" do
      assert Money.DDL.create_money_with_currency() ==
               "CREATE TYPE public.money_with_currency AS (currency_code varchar, amount numeric);"
    end

    test "is dropped by name" do
      assert Money.DDL.drop_money_with_currency() ==
               "DROP TYPE public.money_with_currency;"
    end
  end

  describe "aggregate functions keep their deployed names" do
    test "sum" do
      sql = Money.DDL.define_sum_function()

      assert sql =~
               "CREATE OR REPLACE FUNCTION money_sum_state_function(agg_state money_with_currency, money money_with_currency)"

      assert sql =~ "CREATE OR REPLACE AGGREGATE sum(money_with_currency)"
      assert sql =~ "parallel = SAFE"
    end

    test "min and max" do
      sql = Money.DDL.define_minmax_functions()

      for aggregate <- ["min", "max"] do
        assert sql =~ "CREATE OR REPLACE FUNCTION money_#{aggregate}_state_function("
        assert sql =~ "AGGREGATE #{aggregate}(money_with_currency)"
      end
    end

    test "avg carries its own state type" do
      sql = Money.DDL.define_avg_function()

      assert sql =~ "CREATE TYPE public.money_avg_state AS (currency_code varchar,"
      assert sql =~ "CREATE OR REPLACE FUNCTION money_avg_final_function("
      assert sql =~ "AGGREGATE avg(money_with_currency)"
    end

    test "drops name the functions that were created" do
      assert Money.DDL.drop_sum_function() =~ "DROP AGGREGATE IF EXISTS sum(money_with_currency);"

      assert Money.DDL.drop_minmax_functions() =~
               "DROP AGGREGATE IF EXISTS max(money_with_currency);"

      assert Money.DDL.drop_avg_function() =~ "DROP TYPE IF EXISTS public.money_avg_state;"
    end
  end

  describe "operators" do
    test "the plus operator is commutative and names money_add" do
      sql = Money.DDL.define_plus_operator()

      assert sql =~ "CREATE OR REPLACE FUNCTION money_add("
      assert sql =~ "CREATE OPERATOR + ("
      assert sql =~ "commutator = +"
    end

    # Subtraction is not commutative; the generated operator must not
    # claim that it is.
    test "the minus operator names money_sub and is not commutative" do
      sql = Money.DDL.define_minus_operator()

      assert sql =~ "CREATE OR REPLACE FUNCTION money_sub("
      assert sql =~ "CREATE OPERATOR - ("
      refute sql =~ "commutator"
    end

    # The function defined and the procedure named must agree — they
    # did not in the hand-written SQL this replaced.
    test "the negate operator names the function it defines" do
      sql = Money.DDL.define_negate_operator()

      assert sql =~ "CREATE OR REPLACE FUNCTION money_negate("
      assert sql =~ "procedure = money_negate"
      refute sql =~ "money_neg("
    end

    test "operators are dropped by the same names" do
      assert Money.DDL.drop_plus_operator() =~ "DROP FUNCTION IF EXISTS money_add("
      assert Money.DDL.drop_minus_operator() =~ "DROP FUNCTION IF EXISTS money_sub("
      assert Money.DDL.drop_negate_operator() =~ "DROP FUNCTION IF EXISTS money_negate("
    end
  end

  describe "currency mismatches raise" do
    test "every aggregate and operator raises SQLSTATE 22033 on a currency mismatch" do
      sql =
        Enum.join([
          Money.DDL.define_sum_function(),
          Money.DDL.define_minmax_functions(),
          Money.DDL.define_avg_function(),
          Money.DDL.define_plus_operator()
        ])

      assert sql =~ "Incompatible currency codes"
      assert sql =~ "ERRCODE = '22033'"
    end
  end

  describe "migration wrapping" do
    test "a single statement becomes one execute" do
      assert Money.DDL.execute("SELECT 1;") == ~s|execute "SELECT 1;"|
    end

    test "execute_each emits one execute per statement" do
      wrapped = Money.DDL.execute_each(Money.DDL.drop_sum_function())

      assert length(String.split(wrapped, "\n")) == 3
    end

    test "an append is added to each statement" do
      wrapped = Money.DDL.execute_each(Money.DDL.drop_sum_function(), "|> adjust(repo())")

      assert wrapped =~ "|> adjust(repo())"
    end
  end

  describe "unsupported databases" do
    test "raise rather than emitting the wrong SQL" do
      assert_raise ArgumentError, fn -> Money.DDL.create_money_with_currency(:mysql) end
      assert_raise ArgumentError, fn -> Money.DDL.define_sum_function(:sqlite) end
    end
  end
end
