defmodule Money.DDL do
  @moduledoc """
  Functions to return SQL DDL commands that support the
  creation and deletion of the `money_with_currency` database
  type and associated aggregate functions.

  The SQL is generated by `Localize.Ecto.TaggedDecimal.DDL` from the
  money specification below. A money amount is a tagged decimal — a
  currency code paired with an amount — so it shares the composite type,
  aggregate and operator machinery with other tagged decimals such as
  units, rather than defining its own.
  """

  alias Localize.Ecto.TaggedDecimal
  alias Localize.Ecto.TaggedDecimal.DDL

  @default_db :postgres

  # The composite type `money_with_currency(currency_code, amount)`, its
  # aggregates and operators. The default function names the generator
  # produces — `money_sum_state_function`, `money_add`, `money_sub`,
  # `money_negate` and so on — are exactly those already deployed, so no
  # overrides are needed.
  @money_spec TaggedDecimal.new!(
                type_name: "money_with_currency",
                tag_field: "currency_code",
                value_field: "amount",
                function_prefix: "money",
                argument_name: "money",
                tag_description: "currency code"
              )

  @doc """
  Returns the SQL string which when executed will
  define the `money_with_currency` data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def create_money_with_currency(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.create_type(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the `money_with_currency` data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_money_with_currency(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_type(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  define sum functions for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_sum_function(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_sum_function(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the sum functions for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_sum_function(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_sum_function(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  define min and max functions for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_minmax_functions(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_minmax_functions(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the min and max functions for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_minmax_functions(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_minmax_functions(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  define the avg function for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_avg_function(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_avg_function(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the avg function for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_avg_function(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_avg_function(@money_spec)
  end

  @doc """
  Returns the SQL string which when executed will
  define a `+` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_plus_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_operator(@money_spec, :add)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the `+` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_plus_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_operator(@money_spec, :add)
  end

  @doc """
  Returns the SQL string which when executed will
  define an infix `-` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_minus_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_operator(@money_spec, :subtract)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the infix `-` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_minus_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_operator(@money_spec, :subtract)
  end

  @doc """
  Returns the SQL string which when executed will
  define a unary `-` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def define_negate_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.define_operator(@money_spec, :negate)
  end

  @doc """
  Returns the SQL string which when executed will
  drop the unary `-` operator for the `money_with_currency`
  data type.

  ## Arguments

  * `db_type`: the type of the database for which the SQL
    string should be returned.  Defaults to `:postgres` which
    is currently the only supported database type.

  """
  def drop_negate_operator(db_type \\ @default_db) do
    ensure_postgres!(db_type)
    DDL.drop_operator(@money_spec, :negate)
  end

  @doc ~S"""
  Returns a string that will Ecto `execute` each SQL
  command.

  ## Arguments

  * `sql` is a string of SQL commands that are
    separated by three newlines ("\\n"),
    that is to say two blank lines between commands
    in the file.

  ## Example

      iex> Money.DDL.execute "SELECT name FROM customers;\n\n\nSELECT id FROM orders;"
      "execute \"\"\"\nSELECT name FROM customers;\n\n\nSELECT id FROM orders;\n\"\"\""

  """
  def execute_each(sql, append \\ "") do
    sql
    |> String.split("\n\n\n")
    |> Enum.map_join("\n", &execute(&1, append))
  end

  @doc ~S"""
  Returns a string that will Ecto `execute` a single SQL
  command.

  ## Arguments

  * `sql` is a single SQL command

  ## Example

      iex> Money.DDL.execute "SELECT name FROM customers;"
      "execute \"SELECT name FROM customers;\""

  """
  def execute(sql, append \\ "") do
    sql = String.trim_trailing(sql, "\n")

    if String.contains?(sql, "\n") do
      "execute \"\"\"\n" <> sql <> "\n\"\"\""
    else
      "execute " <> inspect(sql)
    end
    |> Kernel.<>(append)
  end

  defp ensure_postgres!(:postgres), do: :ok

  defp ensure_postgres!(db_type) do
    raise ArgumentError,
          "Database type #{inspect(db_type)} is not supported; only :postgres is available"
  end
end
